/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Entry {
  id?: number;
  joinedTime?: string;
  startedEvent?: number;
  favouriteTeam?: null;
  playerFirstName?: string;
  playerLastName?: string;
  playerRegionId?: number;
  playerRegionName?: string;
  playerRegionIsoCodeShort?: string;
  playerRegionIsoCodeLong?: string;
  summaryOverallPoints?: number;
  summaryOverallRank?: number;
  summaryEventPoints?: number;
  summaryEventRank?: number;
  currentEvent?: number;
  leagues?: {
    classic?: {
      id?: number;
      name?: string;
      shortName?: string | null;
      created?: string;
      closed?: boolean;
      rank?: null;
      maxEntries?: null;
      leagueType?: string;
      scoring?: string;
      adminEntry?: null | number;
      startEvent?: number;
      entryRank?: number;
      entryLastRank?: number;
      entryCanLeave?: boolean;
      entryCanAdmin?: boolean;
      entryCanInvite?: boolean;
      [k: string]: unknown;
    }[];
    h2h?: unknown[];
    cup?: {
      matches?: {
        id?: number;
        entry1Entry?: number;
        entry1Name?: string;
        entry1PlayerName?: string;
        entry1Points?: number;
        entry1Win?: number;
        entry1Draw?: number;
        entry1Loss?: number;
        entry1Total?: number;
        entry2Entry?: number;
        entry2Name?: string;
        entry2PlayerName?: string;
        entry2Points?: number;
        entry2Win?: number;
        entry2Draw?: number;
        entry2Loss?: number;
        entry2Total?: number;
        isKnockout?: boolean;
        winner?: number;
        seedValue?: null;
        event?: number;
        tiebreak?: null;
        [k: string]: unknown;
      }[];
      status?: {
        qualificationEvent?: number;
        qualificationNumbers?: number;
        qualificationRank?: number;
        qualificationState?: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  name?: string;
  kit?: null;
  lastDeadlineBank?: number;
  lastDeadlineValue?: number;
  lastDeadlineTotalTransfers?: number;
  [k: string]: unknown;
}
