/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Elements = {
  chanceOfPlayingNextRound?: number | null;
  chanceOfPlayingThisRound?: number | null;
  code?: number;
  costChangeEvent?: number;
  costChangeEventFall?: number;
  costChangeStart?: number;
  costChangeStartFall?: number;
  dreamteamCount?: number;
  elementType?: number;
  epNext?: string;
  epThis?: string;
  eventPoints?: number;
  firstName?: string;
  form?: string;
  id?: number;
  inDreamteam?: boolean;
  news?: string;
  newsAdded?: string | null;
  nowCost?: number;
  photo?: string;
  pointsPerGame?: string;
  secondName?: string;
  selectedByPercent?: string;
  special?: boolean;
  squadNumber?: null;
  status?: string;
  team?: number;
  teamCode?: number;
  totalPoints?: number;
  transfersIn?: number;
  transfersInEvent?: number;
  transfersOut?: number;
  transfersOutEvent?: number;
  valueForm?: string;
  valueSeason?: string;
  webName?: string;
  minutes?: number;
  goalsScored?: number;
  assists?: number;
  cleanSheets?: number;
  goalsConceded?: number;
  ownGoals?: number;
  penaltiesSaved?: number;
  penaltiesMissed?: number;
  yellowCards?: number;
  redCards?: number;
  saves?: number;
  bonus?: number;
  bps?: number;
  influence?: string;
  creativity?: string;
  threat?: string;
  ictIndex?: string;
  influenceRank?: number;
  influenceRankType?: number;
  creativityRank?: number;
  creativityRankType?: number;
  threatRank?: number;
  threatRankType?: number;
  ictIndexRank?: number;
  ictIndexRankType?: number;
  [k: string]: unknown;
}[];
