/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BootstrapStatic {
  events?: {
    id?: number;
    name?: string;
    deadlineTime?: string;
    averageEntryScore?: number;
    finished?: boolean;
    dataChecked?: boolean;
    highestScoringEntry?: number | null;
    deadlineTimeEpoch?: number;
    deadlineTimeGameOffset?: number;
    highestScore?: number | null;
    isPrevious?: boolean;
    isCurrent?: boolean;
    isNext?: boolean;
    chipPlays?: {
      chipName?: string;
      numPlayed?: number;
      [k: string]: unknown;
    }[];
    mostSelected?: number | null;
    mostTransferredIn?: number | null;
    topElement?: number | null;
    topElementInfo?: {
      id?: number;
      points?: number;
      [k: string]: unknown;
    };
    transfersMade?: number;
    mostCaptained?: number | null;
    mostViceCaptained?: number | null;
    [k: string]: unknown;
  }[];
  gameSettings?: {
    leagueJoinPrivateMax?: number;
    leagueJoinPublicMax?: number;
    leagueMaxSizePublicClassic?: number;
    leagueMaxSizePublicH2h?: number;
    leagueMaxSizePrivateH2h?: number;
    leagueMaxKoRoundsPrivateH2h?: number;
    leaguePrefixPublic?: string;
    leaguePointsH2hWin?: number;
    leaguePointsH2hLose?: number;
    leaguePointsH2hDraw?: number;
    leagueKoFirstInsteadOfRandom?: boolean;
    cupStartEventId?: number;
    cupStopEventId?: number;
    cupQualifyingMethod?: string;
    cupType?: string;
    squadSquadplay?: number;
    squadSquadsize?: number;
    squadTeamLimit?: number;
    squadTotalSpend?: number;
    uiCurrencyMultiplier?: number;
    uiUseSpecialShirts?: boolean;
    uiSpecialShirtExclusions?: unknown[];
    statsFormDays?: number;
    sysViceCaptainEnabled?: boolean;
    transfersSellOnFee?: number;
    leagueH2hTiebreakStats?: string[];
    timezone?: string;
    [k: string]: unknown;
  };
  phases?: {
    id?: number;
    name?: string;
    startEvent?: number;
    stopEvent?: number;
    [k: string]: unknown;
  }[];
  teams?: {
    code?: number;
    draw?: number;
    form?: null;
    id?: number;
    loss?: number;
    name?: string;
    played?: number;
    points?: number;
    position?: number;
    shortName?: string;
    strength?: number;
    teamDivision?: null;
    unavailable?: boolean;
    win?: number;
    strengthOverallHome?: number;
    strengthOverallAway?: number;
    strengthAttackHome?: number;
    strengthAttackAway?: number;
    strengthDefenceHome?: number;
    strengthDefenceAway?: number;
    pulseId?: number;
    [k: string]: unknown;
  }[];
  totalPlayers?: number;
  elements?: {
    chanceOfPlayingNextRound?: number | null;
    chanceOfPlayingThisRound?: number | null;
    code?: number;
    costChangeEvent?: number;
    costChangeEventFall?: number;
    costChangeStart?: number;
    costChangeStartFall?: number;
    dreamteamCount?: number;
    elementType?: number;
    epNext?: string;
    epThis?: string;
    eventPoints?: number;
    firstName?: string;
    form?: string;
    id?: number;
    inDreamteam?: boolean;
    news?: string;
    newsAdded?: string | null;
    nowCost?: number;
    photo?: string;
    pointsPerGame?: string;
    secondName?: string;
    selectedByPercent?: string;
    special?: boolean;
    squadNumber?: null;
    status?: string;
    team?: number;
    teamCode?: number;
    totalPoints?: number;
    transfersIn?: number;
    transfersInEvent?: number;
    transfersOut?: number;
    transfersOutEvent?: number;
    valueForm?: string;
    valueSeason?: string;
    webName?: string;
    minutes?: number;
    goalsScored?: number;
    assists?: number;
    cleanSheets?: number;
    goalsConceded?: number;
    ownGoals?: number;
    penaltiesSaved?: number;
    penaltiesMissed?: number;
    yellowCards?: number;
    redCards?: number;
    saves?: number;
    bonus?: number;
    bps?: number;
    influence?: string;
    creativity?: string;
    threat?: string;
    ictIndex?: string;
    influenceRank?: number;
    influenceRankType?: number;
    creativityRank?: number;
    creativityRankType?: number;
    threatRank?: number;
    threatRankType?: number;
    ictIndexRank?: number;
    ictIndexRankType?: number;
    [k: string]: unknown;
  }[];
  elementStats?: {
    label?: string;
    name?: string;
    [k: string]: unknown;
  }[];
  elementTypes?: {
    id?: number;
    pluralName?: string;
    pluralNameShort?: string;
    singularName?: string;
    singularNameShort?: string;
    squadSelect?: number;
    squadMinPlay?: number;
    squadMaxPlay?: number;
    uiShirtSpecific?: boolean;
    subPositionsLocked?: number[];
    elementCount?: number;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
