/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EventStatus {
  /**
   * This interface was referenced by `EventStatus`'s JSON-Schema definition
   * via the `patternProperty` "^(+)+$".
   */
  [k: string]: {
    bonusAdded?: boolean;
    date?: string;
    event?: number;
    points?: string;
    [k: string]: unknown;
  }[];
}
