/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LeagueStandings {
  league?: {
    id?: number;
    name?: string;
    created?: string;
    closed?: boolean;
    maxEntries?: null;
    leagueType?: string;
    scoring?: string;
    adminEntry?: null;
    startEvent?: number;
    codePrivacy?: string;
    rank?: null;
    [k: string]: unknown;
  };
  newEntries?: {
    hasNext?: boolean;
    page?: number;
    results?: unknown[];
    [k: string]: unknown;
  };
  standings?: {
    hasNext?: boolean;
    page?: number;
    results?: {
      id?: number;
      eventTotal?: number;
      playerName?: string;
      rank?: number;
      lastRank?: number;
      rankSort?: number;
      total?: number;
      entry?: number;
      entryName?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
